on: [workflow_dispatch]

jobs:
  Publish:
    runs-on: ubuntu-latest
    name: Snap Action
    steps:
      - uses: actions/checkout@v2
      - name: Run composite snap-action
        uses: ./
        with:
        # required
          repository: ${{ env.GITHUB_REPOSITORY }}